networks:
  robot-network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  robot-emulator:
    build: .
    image: runswift/v6r:latest
    container_name: docker_robot
    hostname: vrobot
    # networks:
    #   robot-network:
    #     ipv4_address: 10.0.0.137
    ports:
      - "24:22"